[package]
edition = "2021"
name = "wasmreftest"
version = "0.1.0"

[dependencies]
wasm-bindgen = "^0.2.79"
web-sys = {version = "^0.3.56", features = ["console"]}
wee_alloc = "^0.4.5"

[lib]
crate-type = ["cdylib"]
